---
- name: Deploy hello-world-microservice to Docker Swarm
  hosts: swarm-managers
  vars:
    docker_image: "your-docker-registry/hello-world-microservice:{{ commit_hash }}"

  tasks:
    - name: Pull new Docker image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        # source: ?

    - name: Update Docker service
      docker_service:
        project_name: hello-world
        definition:
          version: "3"
          services:
            web:
              image: "{{ docker_image }}"
              deploy:
                update_config:
                  parallelism: 2
                  delay: 10s
                  failure_action: rollback
                  order: start-first